# Generated by Django 5.0.4 on 2024-04-23 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spring', models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], max_length=2)),
                ('summer', models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], max_length=2)),
                ('autumn', models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], max_length=2)),
                ('winter', models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('fam', models.CharField(max_length=100, verbose_name='surname')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('otc', models.CharField(blank=True, max_length=200, null=True, verbose_name='patronymic')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('other_titles', models.CharField(max_length=100)),
                ('connect', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Создан'), ('pending', 'На проверке'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], max_length=20)),
                ('coord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST.coord')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='REST.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='REST.perevaladded')),
            ],
        ),
    ]
