# Generated by Django 5.0.4 on 2024-04-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0003_rename_beautytitle_perevaladded_beauty_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevaladded',
            old_name='coord',
            new_name='coords',
        ),
    ]
