# Generated by Django 5.0.4 on 2024-04-24 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0005_remove_image_pereval_perevaladded_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perevaladded',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='pereval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='REST.perevaladded'),
        ),
    ]
