# Generated by Django 5.0.4 on 2024-04-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0006_remove_perevaladded_images_image_pereval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(choices=[('new', 'Создан'), ('pending', 'На проверке'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
